apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "colourserver.fullname" . }}
  labels:
    app: {{ template "colourserver.name" . }}
    chart: {{ template "colourserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "colourserver.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/path: '/metrics'
          prometheus.io/port: '8080'
      labels:
        app: {{ template "colourserver.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources: {}
