apiVersion: v1
kind: Service
metadata:
  name: {{ template "colourserver.fullname" . }}
  labels:
    app: {{ template "colourserver.name" . }}
    chart: {{ template "colourserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: 8080
      name: http
      protocol: TCP
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "colourserver.name" . }}
    release: {{ .Release.Name }}
